### ISSUE TITLE
Can you explain its purpose, I'm confused

### ISSUE THREAD

**Issue by ovizii** [iadgov/goSecure#21]
Hi there,

I read about gosecure on a website which mentioned it so I visited your website and read the documentation and I'm sure I could set it up but I am confused or maybe I am missing the point but why would I install the client on a PI when I could as well install the necessary software on the client device itself? 

I mean if I look at this drawing: https://iadgov.github.io/goSecure/documentation.html#documentation 

normally I#d install a VPN Server on the corporate network and a VPN client on the corporate laptop to allow secure access to corporate resources. 

I fail to see the benefit of gosecure, could someone please explain what I am missing?

**Comment by squadramunter** [comment]
I think the way it's mean is that they want to setup a VPN tunnel over a network connection rather than connect a client to a VPN. The network you are working on is the VPN itself. So if I am right you must setup a server that serves the VPN connection and finally you need to setup a VPN network bridge. so the WAN connects to the outside world and then it connect's to that VPN what you created. then if you have a raspberry pi you can setup the client to make it a VPN network bridge that serves this VPN tunnel to force everyone to connect's to that VPN tunnel. I created also one but not as this. they are using a salt and a strong password hash method. I need to go deeper in this working method so I can explain a lot more. If I am wrong pls correct me.

**Comment by iadgovuser1** [comment]
One of the uses cases was to provide an easy to config, low cost VPN connectivity solution when you don't have a device (e.g. corporate laptop) that you own or trust (e.g. traveling).

**Comment by ovizii** [comment]
oh, ok, I see, so its more about being able to surf safely while on-the-move using any device rather than being able to access secure stuff remotely while on-the-move as I saw it as defeating the purpose in the second case (what I mean is that when I am on-the-move say at an internet cafe where I don't have any control over the device I don't really want to open a VPN straight to my private network at home). 

Case one makes sense, say I am somewhere using an unsafe device I would understand why using an external device which connects to a VPN server running somewhere at home in a DMZ or separate network woudl make sense.
